name: Benchmark PR

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  benchmark:
    name: Benchmark - Julia ${{ matrix.julia-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ["1"]
    
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: ${{ matrix.julia-version }}
          script: "benchmark/benchmarks.jl"
