name: Benchmark a pull request

on:
  pull_request_target:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
    generate_plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
              with:
                ssh-key: '-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQEA0WCSpJyMw69Q6CxR9Pzidn5ban5m8lfJU2Lig/1jzqabD1Ak
AR/pQNGBx4fGC8li6JQpVoUZBJluKWYv3aP5wpnFDKMdmY5rb5SFbzj1jA+uqNxB
RvWLPNPD9PRbl8o3jzwzCKvzW9REQhSRoflK1SOG5MdpVOY/+2SMUFSpiBTTlpmr
goVepjprdOLRmsZlSDakuFdsPhMWbQzmO27mIJaOYEDlxlo8nPd7BxPieewQlgCg
c1lowfut33mxx8fx0N583kbWnOCb41WKkdiKOEExkZzpz29GS3q6wPRqkUKIyUVL
dgG++i0LX8pCmKaTf4Ahjk+lOC0eLDfFaTbVAQIDAQABAoIBAQCuOmVsk1TTVWTG
/nJoobK1FapucKarzP8b43JIkSdng94OHQsI4IwRwwTyi3nyvu8OSJQpifHqkN5J
lt4H2nZwR9LgFDACYq/mFrn+dnBlz3rwyu+K47KsuC8c++Xn5n7bMyXodmW4qWbv
cfxJw49Q0xJh98ofusXNJLtZ8UltkR0QukqqQlEk4fMJCycUrDnh/NLwj98aUY75
0AScAie0UjiN66bbJvv+kmna6aSYPzuvmzhs8Q0XFerJ5Fhvv3tEpc9CNPnoDIGQ
2Ybp/42kjgOHeBQMDbRNvPoJCPgXPPflwk908U+EhRWs/KNPU+HAdvxV6EGd83hn
oiQG6+QBAoGBAPWjlT00FcXQZxg8767Y5xr18vi+m7LAxo6amd49da3hMwXl3S0R
i1iq7TR4ya3/DVipE5VsY0o6YA2hgTyKgauFxLkz7GN0g8IQwxB+V73Av9M8DkDh
KECmUq7vuDTXI9PcmWmpZFryvbiOry8G/HPnipGXJLAJxy87gggnHFthAoGBANo1
bzCiuvhtfIA8fPoFhim6cKz8134WdZNXCIWTp6nYh3Q3lIrmn8YRmizhq9LqYKtS
faYWGk6USXkHABzbG+2GWdOza+XUCcr8sqIqyzCc8rqoemDdQd7sztG55AhmBvU9
0KCh+52szh9kIxaOAIxutSFYrabxBUqgpuNpo32hAoGBAK9gjuH2uQDV7XVxtFLq
y/4E0efk9vcmCd2w5eC1krqFic9RMZvG5e11hAwtnRjce+PsO244x58slH3G7KWT
4kbbJ/xu5PyRKK07GHpDKlPxNUQUobySxRF7bpc10hfv7sWJwAKfjWYd33TQcqUp
4L7D9rxB5FDHem3vl8RIYEehAoGBANWHAmZiZ3ngkbte9aEntLCyu73bsfe1fJqQ
yUsFQUVoGKy2EsqVgXWuFeOjdaNwLOaZU1EqQdXxL7CaFBcopjyZgt8xrPz6sBaN
jzQ3khvhCXl0kkSlXucJbh02vZkmVdq4Aaaeu/0Ac7euItPYY1sInoCiKVO6eMYd
TRIudojhAoGBAL2hDQFkE0YHGTCwMqsbcSXye8TGGR6K26cg/tY1IbQHnlZIiJCj
zlDcczDhEziP1YeoKzJW1CCgdsl7Bl7rSHXQnF5a5YIhyjIvqp7ayNxirJvfobGn
qW50sbHy7HcfNBufdzUU6Z2MfSPasTkc3jBcwbGEwVZmM+zQdIwwki8g
-----END RSA PRIVATE KEY-----
'
            - uses: julia-actions/setup-julia@v1
              with:
                version: "1.11"
            - uses: julia-actions/cache@v2
            - name: Extract Package Name from Project.toml
              id: extract-package-name
              run: |
                PACKAGE_NAME=$(grep "^name" Project.toml | sed 's/^name = "\(.*\)"$/\1/')
                echo "::set-output name=package_name::$PACKAGE_NAME"
            - name: Build AirspeedVelocity
              env:
                JULIA_NUM_THREADS: 2
              run: |
                # Lightweight build step, as sometimes the runner runs out of memory:
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.add(;url="https://github.com/MilesCranmer/AirspeedVelocity.jl.git")'
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.build("AirspeedVelocity")'
            - name: Add ~/.julia/bin to PATH
              run: |
                echo "$HOME/.julia/bin" >> $GITHUB_PATH
            - name: Run benchmarks
              run: |
                echo $PATH
                ls -l ~/.julia/bin
                mkdir results
                benchpkg ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.repository.default_branch}},${{github.event.pull_request.head.sha}}" --url=${{ github.event.repository.clone_url }} --bench-on="${{github.event.pull_request.head.sha}}" --output-dir=results/ --tune
            - name: Create plots from benchmarks
              run: |
                mkdir -p plots
                benchpkgplot ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.repository.default_branch}},${{github.event.pull_request.head.sha}}" --npart=10 --format=png --input-dir=results/ --output-dir=plots/
            - name: Upload plot as artifact
              uses: actions/upload-artifact@v2
              with:
                name: plots
                path: plots
            - name: Create markdown table from benchmarks
              run: |
                benchpkgtable ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.repository.default_branch}},${{github.event.pull_request.head.sha}}" --input-dir=results/ --ratio > table.md
                echo '### Benchmark Results' > body.md
                echo '' >> body.md
                echo '' >> body.md
                cat table.md >> body.md
                echo '' >> body.md
                echo '' >> body.md
                echo '### Benchmark Plots' >> body.md
                echo 'A plot of the benchmark results have been uploaded as an artifact to the workflow run for this PR.' >> body.md
                echo 'Go to "Actions"->"Benchmark a pull request"->[the most recent run]->"Artifacts" (at the bottom).' >> body.md

            - name: Find Comment
              uses: peter-evans/find-comment@v2
              id: fcbenchmark
              with:
                issue-number: ${{ github.event.pull_request.number }}
                comment-author: 'github-actions[bot]'
                body-includes: Benchmark Results

            - name: Comment on PR
              uses: peter-evans/create-or-update-comment@v5
              with:
                comment-id: ${{ steps.fcbenchmark.outputs.comment-id }}
                issue-number: ${{ github.event.pull_request.number }}
                body-path: body.md
                edit-mode: replace