# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "data/**"
      - "notebooks/**"
      - "plots/**"
      - "examples/**"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "data/**"
      - "notebooks/**"
      - "plots/**"
      - "examples/**"

jobs:
  # formatter:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       julia-version: [1]
  #       julia-arch: [x86]
  #       os: [ubuntu-latest]
  #   steps:
  #     - uses: julia-actions/setup-julia@latest
  #       with:
  #         version: ${{ matrix.julia-version }}

  #     - uses: actions/checkout@v4
  #     - name: Install JuliaFormatter and format
  #       # This will use the latest version by default but you can set the version like so:
  #       #
  #       # julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="0.13.0"))'
  #       run: |
  #         julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="1.0.56"))'
  #         julia  -e 'using JuliaFormatter; format(".", verbose=true)'
  #     - name: Format check
  #       run: |
  #         julia -e '
  #         out = Cmd(`git diff`) |> read |> String
  #         if out == ""
  #             exit(0)
  #         else
  #             @error "Some files have not been formatted !!!"
  #             write(stdout, out)
  #             exit(1)
  #         end'

  # --url=${{ github.event.repository.clone_url }}

  generate_plots:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@v1
          with:
            version: "1.11"
        - uses: julia-actions/cache@v2
        - name: Extract Package Name from Project.toml
          id: extract-package-name
          run: |
            PACKAGE_NAME=$(grep "^name" Project.toml | sed 's/^name = "\(.*\)"$/\1/')
            echo "::set-output name=package_name::$PACKAGE_NAME"
        - name: Build AirspeedVelocity
          env:
            JULIA_NUM_THREADS: 2
          run: |
            # Lightweight build step, as sometimes the runner runs out of memory:
            julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.add(;url="https://github.com/MilesCranmer/AirspeedVelocity.jl.git")'
            julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.build("AirspeedVelocity")'
        - name: Add ~/.julia/bin to PATH
          run: |
            echo "$HOME/.julia/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: |
            echo $PATH
            ls -l ~/.julia/bin
            mkdir results
            benchpkg ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.repository.default_branch}},${{github.event.pull_request.head.sha}}" --bench-on="${{github.event.repository.default_branch}}" --output-dir=results/ --tune
        - name: Create plots from benchmarks
          run: |
            mkdir -p plots
            benchpkgplot ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.repository.default_branch}},${{github.event.pull_request.head.sha}}" --npart=10 --format=png --input-dir=results/ --output-dir=plots/
        - name: Upload plot as artifact
          uses: actions/upload-artifact@v2
          with:
            name: plots
            path: plots
        - name: Create markdown table from benchmarks
          run: |
            benchpkgtable ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.repository.default_branch}},${{github.event.pull_request.head.sha}}" --input-dir=results/ --ratio > table.md
            echo '### Benchmark Results' > body.md
            echo '' >> body.md
            echo '' >> body.md
            cat table.md >> body.md
            echo '' >> body.md
            echo '' >> body.md
            echo '### Benchmark Plots' >> body.md
            echo 'A plot of the benchmark results have been uploaded as an artifact to the workflow run for this PR.' >> body.md
            echo 'Go to "Actions"->"Benchmark a pull request"->[the most recent run]->"Artifacts" (at the bottom).' >> body.md
        - name: Find Comment
          uses: peter-evans/find-comment@v2
          id: fcbenchmark
          with:
            issue-number: ${{ github.event.pull_request.number }}
            comment-author: 'github-actions[bot]'
            body-includes: Benchmark Results
        - name: Comment on PR
          uses: peter-evans/create-or-update-comment@v3
          with:
            comment-id: ${{ steps.fcbenchmark.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body-path: body.md
            edit-mode: replace


  testAPCE:
    name: APCE (${{ matrix.group }}) - ${{ matrix.version }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: x64
      - uses: julia-actions/cache@v2
      - name: Update registry
        run: julia -e 'using Pkg; Pkg.Registry.update()'
      - uses: julia-actions/julia-runtest@v1


  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Julia
  #       uses: julia-actions/setup-julia@v1
  #       with:
  #         version: '1.10.4'

  #     - name: Install dependencies
  #       run: julia --project -e 'using Pkg; Pkg.instantiate()'

  #     - name: Run tests
  #       run: julia --project -e 'using Pkg; Pkg.test()'

  #     - name: Run performance checks
  #       run: julia --project perfchecker_config.jl
